version: '3.8'
services:
  imgproxy:
    image: ghcr.io/aaacoder-ds/imgproxy:latest
    container_name: imgproxy
    restart: unless-stopped
    ports:
      - '3083:8080'
    environment:
      - IMGPROXY_BIND=:8080
      - IMGPROXY_NETWORK_TIMEOUT=30
      - IMGPROXY_TIMEOUT=30
      - IMGPROXY_READ_REQUEST_TIMEOUT=30
      - IMGPROXY_DOWNLOAD_TIMEOUT=30
      - IMGPROXY_MAX_REDIRECTS=5
      - IMGPROXY_PATH_PREFIX=
      - IMGPROXY_IGNORE_SSL_VERIFICATION=false
      - IMGPROXY_CONCURRENCY=4
      - IMGPROXY_MAX_CLIENTS=50
      - IMGPROXY_TTL=604800
      - IMGPROXY_CACHE_SIZE=500
      - IMGPROXY_CACHE_CLEANUP_INTERVAL=3600
      - IMGPROXY_QUALITY=85
      - IMGPROXY_FORMAT_QUALITY=jpeg=85,webp=85,avif=75
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_PNG_INTERLACED=true
      - IMGPROXY_KEY=${SECRET}
      - IMGPROXY_SALT=${SALT}
      - IMGPROXY_ALLOWED_SOURCES=*
      - IMGPROXY_ALLOW_ORIGIN=*
      - IMGPROXY_WATERMARK_DATA=
      - IMGPROXY_WATERMARK_URL=
      - IMGPROXY_WATERMARK_OPACITY=0.6
      - IMGPROXY_STRIP_METADATA=true
      - IMGPROXY_STRIP_COLOR_PROFILE=true
      - IMGPROXY_AUTO_ROTATE=true
      - IMGPROXY_ENFORCE_THUMBNAIL=false
      - IMGPROXY_ENABLE_CLIENT_HINTS=true
      - IMGPROXY_ENABLE_TRUE_COLOR=true
      - IMGPROXY_ENABLE_SHARPR=false
      - IMGPROXY_ENABLE_AVIF=true
      - IMGPROXY_ENABLE_WEBP=true
      - IMGPROXY_ENABLE_JXL=false
      - IMGPROXY_ENABLE_HEIC=true
      - IMGPROXY_ENABLE_BMP=true
      - IMGPROXY_ENABLE_ICO=true
      - IMGPROXY_ENABLE_TIFF=true
      - IMGPROXY_ENABLE_GIF=true
      - IMGPROXY_ENABLE_PDF=false
      - IMGPROXY_ENABLE_SVG=true
      - IMGPROXY_ENABLE_VIDEO_THUMBNAILS=false
      - IMGPROXY_MAX_ANIMATION_FRAMES=300
      - IMGPROXY_MAX_SRC_RESOLUTION=268435456
      - IMGPROXY_MAX_SRC_FILE_SIZE=10485760
      - IMGPROXY_MAX_ANIMATION_FRAME_RESOLUTION=268435456
      - IMGPROXY_MAX_SVG_CHECK_BYTES=65536
      - IMGPROXY_SANITIZE_SVG=true
      - IMGPROXY_MAX_MEMORY_USAGE=268435456
      - IMGPROXY_MAX_IMAGE_RESOLUTION=268435456
      - IMGPROXY_RETURN_ATTACHMENT=false
      - IMGPROXY_RETURN_ERROR_BODY=true
      - IMGPROXY_USE_SHORT_OPTIONS=false
      - IMGPROXY_LOG_LEVEL=info
      - IMGPROXY_LOG_FORMAT=json
      - IMGPROXY_DEVELOPMENT_ERRORS_MODE=false
      - IMGPROXY_IGNORE_SSL_VERIFICATION=false
    volumes:
      - /mnt/sdb/img:/data
    healthcheck:
      test:
        - CMD
        - wget
        - '-qO-'
        - http://localhost:8080/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.img-app-oqievs-11-web.rule=Host(`img.aaacoder.xyz`)
      - traefik.http.routers.img-app-oqievs-11-web.entrypoints=web
      - traefik.http.services.img-app-oqievs-11-web.loadbalancer.server.port=8080
      - traefik.http.routers.img-app-oqievs-11-web.service=img-app-oqievs-11-web
      - traefik.http.routers.img-app-oqievs-11-web.middlewares=redirect-to-https@file
      - traefik.http.routers.img-app-oqievs-11-websecure.rule=Host(`img.aaacoder.xyz`)
      - traefik.http.routers.img-app-oqievs-11-websecure.entrypoints=websecure
      - traefik.http.services.img-app-oqievs-11-websecure.loadbalancer.server.port=8080
      - traefik.http.routers.img-app-oqievs-11-websecure.service=img-app-oqievs-11-web
      - traefik.http.routers.img-app-oqievs-11-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
