version: '3.8'

services:
  imgproxy:
    image: ghcr.io/aaacoder-ds/imgproxy:latest
    container_name: imgproxy
    restart: unless-stopped
    ports:
      - "3083:8080"
    environment:
      # Basic configuration
      - IMGPROXY_BIND=:8080
      - IMGPROXY_NETWORK_TIMEOUT=30
      - IMGPROXY_READ_TIMEOUT=30
      - IMGPROXY_WRITE_TIMEOUT=30
      - IMGPROXY_DOWNLOAD_TIMEOUT=30
      - IMGPROXY_MAX_REDIRECTS=5
      
      # Performance and concurrency
      - IMGPROXY_CONCURRENCY=4
      - IMGPROXY_MAX_CLIENTS=50
      
      # Cache configuration with periodic cleanup
      - IMGPROXY_TTL=604800
      - IMGPROXY_CACHE_SIZE=500
      - IMGPROXY_CACHE_CLEANUP_INTERVAL=3600
      
      # Image quality settings
      - IMGPROXY_QUALITY=85
      - IMGPROXY_FORMAT_QUALITY=jpeg=85,webp=85,avif=75
      - IMGPROXY_JPEG_PROGRESSIVE=true
      - IMGPROXY_PNG_INTERLACED=true
      
      # Security settings for public access
      - IMGPROXY_SECRET=${SECRET}
      - IMGPROXY_SALT=${SALT}
      - IMGPROXY_ALLOWED_SOURCES=*
      - IMGPROXY_ALLOW_ORIGIN=*
      
      # Watermark settings (disabled for public use)
      - IMGPROXY_WATERMARK_DATA=
      - IMGPROXY_WATERMARK_URL=
      - IMGPROXY_WATERMARK_OPACITY=0
      
      # Image processing settings
      - IMGPROXY_STRIP_METADATA=true
      - IMGPROXY_STRIP_COLOR_PROFILE=true
      - IMGPROXY_AUTO_ROTATE=true
      - IMGPROXY_ENFORCE_THUMBNAIL=false
      - IMGPROXY_ENABLE_CLIENT_HINTS=true
      - IMGPROXY_ENABLE_TRUE_COLOR=true
      - IMGPROXY_ENABLE_SHARPR=false
      
      # Format support
      - IMGPROXY_ENABLE_AVIF=true
      - IMGPROXY_ENABLE_WEBP=true
      - IMGPROXY_ENABLE_JXL=false
      - IMGPROXY_ENABLE_HEIC=true
      - IMGPROXY_ENABLE_BMP=true
      - IMGPROXY_ENABLE_ICO=true
      - IMGPROXY_ENABLE_TIFF=true
      - IMGPROXY_ENABLE_GIF=true
      - IMGPROXY_ENABLE_PDF=false
      - IMGPROXY_ENABLE_SVG=true
      - IMGPROXY_ENABLE_VIDEO_THUMBNAILS=false
      
      # Limits for public access
      - IMGPROXY_MAX_ANIMATION_FRAMES=300
      - IMGPROXY_MAX_SRC_RESOLUTION=268435456
      - IMGPROXY_MAX_SRC_FILE_SIZE=10485760
      - IMGPROXY_MAX_ANIMATION_FRAME_RESOLUTION=268435456
      - IMGPROXY_MAX_SVG_CHECK_BYTES=65536
      - IMGPROXY_SANITIZE_SVG=true
      - IMGPROXY_MAX_MEMORY_USAGE=268435456
      - IMGPROXY_MAX_IMAGE_RESOLUTION=268435456
      
      # Response settings
      - IMGPROXY_RETURN_ATTACHMENT=false
      - IMGPROXY_RETURN_ERROR_BODY=true
      
      # Logging
      - IMGPROXY_LOG_LEVEL=info
      - IMGPROXY_LOG_FORMAT=json
      
    volumes:
      - /mnt/sdb/img:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
